// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwccespcjudnorwowzst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3Y2Nlc3BjanVkbm9yd293enN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0Njk3NDgsImV4cCI6MjA3NDA0NTc0OH0.c3WAjN8llDEbZwCrS4NglIKYnKhYZoiqLvI1VonFk38";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});